const db = {
  users: [
    {
      UserID: 1,
      UserName: "john_doe",
      Email: "john@example.com",
      PasswordHash: "hashed_password_1",
      CreatedAt: "2024-09-01T10:00:00Z",
    },
    {
      UserID: 2,
      UserName: "jane_smith",
      Email: "jane@example.com",
      PasswordHash: "hashed_password_2",
      CreatedAt: "2024-09-02T12:30:00Z",
    },
  ],
  sessions: [
    {
      SessionID: 1,
      UserID: 1,
      SessionToken: "token_abc123",
      CreatedAt: "2024-09-01T10:00:00Z",
      ExpiresAt: "2024-09-02T10:00:00Z",
    },
    {
      SessionID: 2,
      UserID: 2,
      SessionToken: "token_xyz789",
      CreatedAt: "2024-09-02T12:30:00Z",
      ExpiresAt: "2024-09-03T12:30:00Z",
    },
  ],
  recipes: [
    {
      RecipeID: 1,
      UserID: 1,
      RecipeName: "Green Mojito Smoothie",
      CreatedAt: "2024-09-01T15:00:00Z",
    },
    {
      RecipeID: 2,
      UserID: 2,
      RecipeName: "Tropical Orange Creamsicle Smoothie",
      CreatedAt: "2024-09-02T18:00:00Z",
    },
  ],
  ingredients: [
    {
      IngredientID: 1,
      IngredientName: "Almond milk",
      Category: "LIQUID",
      VitaminA: 500,
      VitaminC: 0,
      Calcium: 450,
      Iron: 0.7,
      Potassium: 160,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 2,
      IngredientName: "Oat milk",
      Category: "LIQUID",
      VitaminA: 350,
      VitaminC: 0,
      Calcium: 350,
      Iron: 1.0,
      Potassium: 389,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 3,
      IngredientName: "Coconut water",
      Category: "LIQUID",
      VitaminA: 0,
      VitaminC: 2.4,
      Calcium: 60,
      Iron: 0.7,
      Potassium: 600,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 4,
      IngredientName: "Filtered water",
      Category: "LIQUID",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 0,
      Iron: 0,
      Potassium: 0,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 5,
      IngredientName: "Apple",
      Category: "FRUIT",
      VitaminA: 98,
      VitaminC: 8.4,
      Calcium: 10,
      Iron: 0.22,
      Potassium: 195,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 6,
      IngredientName: "Avocado",
      Category: "FRUIT",
      VitaminA: 293,
      VitaminC: 15,
      Calcium: 18,
      Iron: 0.8,
      Potassium: 708,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 7,
      IngredientName: "Banana",
      Category: "FRUIT",
      VitaminA: 76,
      VitaminC: 10.3,
      Calcium: 6,
      Iron: 0.31,
      Potassium: 450,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 8,
      IngredientName: "Blueberries",
      Category: "FRUIT",
      VitaminA: 80,
      VitaminC: 14.4,
      Calcium: 9,
      Iron: 0.41,
      Potassium: 114,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 9,
      IngredientName: "Coconut",
      Category: "FRUIT",
      VitaminA: 0,
      VitaminC: 2.8,
      Calcium: 11,
      Iron: 1.94,
      Potassium: 285,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 10,
      IngredientName: "Cherries",
      Category: "FRUIT",
      VitaminA: 88,
      VitaminC: 10.8,
      Calcium: 17,
      Iron: 0.5,
      Potassium: 306,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 11,
      IngredientName: "Kiwi",
      Category: "FRUIT",
      VitaminA: 87,
      VitaminC: 164,
      Calcium: 34,
      Iron: 0.3,
      Potassium: 562,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 12,
      IngredientName: "Mango",
      Category: "FRUIT",
      VitaminA: 1785,
      VitaminC: 60,
      Calcium: 21,
      Iron: 0.2,
      Potassium: 277,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 13,
      IngredientName: "Melon",
      Category: "FRUIT",
      VitaminA: 5406,
      VitaminC: 59.2,
      Calcium: 15,
      Iron: 0.4,
      Potassium: 473,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 14,
      IngredientName: "Orange",
      Category: "FRUIT",
      VitaminA: 295,
      VitaminC: 95.8,
      Calcium: 72,
      Iron: 0.2,
      Potassium: 326,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 15,
      IngredientName: "Peach",
      Category: "FRUIT",
      VitaminA: 489,
      VitaminC: 9.9,
      Calcium: 9,
      Iron: 0.4,
      Potassium: 285,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 16,
      IngredientName: "Pear",
      Category: "FRUIT",
      VitaminA: 38,
      VitaminC: 7.5,
      Calcium: 15,
      Iron: 0.32,
      Potassium: 206,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 17,
      IngredientName: "Pineapple",
      Category: "FRUIT",
      VitaminA: 58,
      VitaminC: 78.9,
      Calcium: 21,
      Iron: 0.5,
      Potassium: 180,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 18,
      IngredientName: "Strawberries",
      Category: "FRUIT",
      VitaminA: 17,
      VitaminC: 89.4,
      Calcium: 24,
      Iron: 0.68,
      Potassium: 220,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 19,
      IngredientName: "Raspberries",
      Category: "FRUIT",
      VitaminA: 41,
      VitaminC: 32.2,
      Calcium: 31,
      Iron: 0.9,
      Potassium: 186,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 20,
      IngredientName: "Beets",
      Category: "VEGETABLES",
      VitaminA: 44,
      VitaminC: 6.7,
      Calcium: 22,
      Iron: 1.1,
      Potassium: 442,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 21,
      IngredientName: "Carrots",
      Category: "VEGETABLES",
      VitaminA: 21383,
      VitaminC: 7.2,
      Calcium: 42,
      Iron: 0.38,
      Potassium: 410,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 22,
      IngredientName: "Cauliflower",
      Category: "VEGETABLES",
      VitaminA: 0,
      VitaminC: 51.6,
      Calcium: 24,
      Iron: 0.41,
      Potassium: 320,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 23,
      IngredientName: "Celery",
      Category: "VEGETABLES",
      VitaminA: 453,
      VitaminC: 3.1,
      Calcium: 44,
      Iron: 0.2,
      Potassium: 263,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 24,
      IngredientName: "Collard greens",
      Category: "VEGETABLES",
      VitaminA: 7228,
      VitaminC: 34.6,
      Calcium: 266,
      Iron: 0.34,
      Potassium: 222,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 25,
      IngredientName: "Cucumber",
      Category: "VEGETABLES",
      VitaminA: 109,
      VitaminC: 4.7,
      Calcium: 19,
      Iron: 0.33,
      Potassium: 193,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 26,
      IngredientName: "Kale",
      Category: "VEGETABLES",
      VitaminA: 10302,
      VitaminC: 80.4,
      Calcium: 90,
      Iron: 1.2,
      Potassium: 299,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 27,
      IngredientName: "Sweet potato",
      Category: "VEGETABLES",
      VitaminA: 18443,
      VitaminC: 35.3,
      Calcium: 68,
      Iron: 0.88,
      Potassium: 448,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 28,
      IngredientName: "Romaine",
      Category: "VEGETABLES",
      VitaminA: 4094,
      VitaminC: 11.3,
      Calcium: 16,
      Iron: 0.76,
      Potassium: 232,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 29,
      IngredientName: "Spinach",
      Category: "VEGETABLES",
      VitaminA: 2813,
      VitaminC: 24.9,
      Calcium: 30,
      Iron: 0.81,
      Potassium: 167,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 30,
      IngredientName: "Zucchini",
      Category: "VEGETABLES",
      VitaminA: 392,
      VitaminC: 22.2,
      Calcium: 18,
      Iron: 0.46,
      Potassium: 325,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 31,
      IngredientName: "Black beans",
      Category: "GRAINS",
      VitaminA: 17,
      VitaminC: 0,
      Calcium: 46,
      Iron: 3.6,
      Potassium: 611,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 32,
      IngredientName: "Buckwheat",
      Category: "GRAINS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 18,
      Iron: 1.3,
      Potassium: 148,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 33,
      IngredientName: "Millet",
      Category: "GRAINS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 5,
      Iron: 1.1,
      Potassium: 108,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 34,
      IngredientName: "Oats",
      Category: "GRAINS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 54,
      Iron: 3.4,
      Potassium: 164,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 35,
      IngredientName: "Quinoa",
      Category: "GRAINS",
      VitaminA: 14,
      VitaminC: 0,
      Calcium: 31,
      Iron: 2.8,
      Potassium: 318,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 36,
      IngredientName: "Tofu",
      Category: "GRAINS",
      VitaminA: 178,
      VitaminC: 0,
      Calcium: 253,
      Iron: 3.4,
      Potassium: 121,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 37,
      IngredientName: "Edamame",
      Category: "GRAINS",
      VitaminA: 23,
      VitaminC: 9.5,
      Calcium: 98,
      Iron: 2.3,
      Potassium: 676,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 38,
      IngredientName: "White beans",
      Category: "GRAINS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 161,
      Iron: 6.6,
      Potassium: 829,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 39,
      IngredientName: "Almonds",
      Category: "NUTS",
      VitaminA: 1,
      VitaminC: 0,
      Calcium: 243,
      Iron: 5.3,
      Potassium: 733,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 40,
      IngredientName: "Brazil nuts",
      Category: "NUTS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 213,
      Iron: 2.4,
      Potassium: 872,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 41,
      IngredientName: "Cashews",
      Category: "NUTS",
      VitaminA: 0,
      VitaminC: 0.1,
      Calcium: 37,
      Iron: 5.1,
      Potassium: 660,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 42,
      IngredientName: "Chia seeds",
      Category: "NUTS",
      VitaminA: 0,
      VitaminC: 1.6,
      Calcium: 631,
      Iron: 7.7,
      Potassium: 407,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 43,
      IngredientName: "Flaxseeds",
      Category: "NUTS",
      VitaminA: 0,
      VitaminC: 0.6,
      Calcium: 428,
      Iron: 9.6,
      Potassium: 1155,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 44,
      IngredientName: "Hemp seeds",
      Category: "NUTS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 70,
      Iron: 9.5,
      Potassium: 1200,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 45,
      IngredientName: "Macadamia nuts",
      Category: "NUTS",
      VitaminA: 0,
      VitaminC: 0.7,
      Calcium: 114,
      Iron: 4.9,
      Potassium: 401,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 46,
      IngredientName: "Acai",
      Category: "SUPERFOODS",
      VitaminA: 750,
      VitaminC: 15,
      Calcium: 35,
      Iron: 1.5,
      Potassium: 105,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 47,
      IngredientName: "Camu camu",
      Category: "SUPERFOODS",
      VitaminA: 0,
      VitaminC: 2800,
      Calcium: 27,
      Iron: 0.5,
      Potassium: 83,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 48,
      IngredientName: "Cacao (or cocoa)",
      Category: "SUPERFOODS",
      VitaminA: 2,
      VitaminC: 0.1,
      Calcium: 56,
      Iron: 7.2,
      Potassium: 427,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 49,
      IngredientName: "Cinnamon",
      Category: "SUPERFOODS",
      VitaminA: 295,
      VitaminC: 0.3,
      Calcium: 280,
      Iron: 1.5,
      Potassium: 116,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 50,
      IngredientName: "Chlorella",
      Category: "SUPERFOODS",
      VitaminA: 2870,
      VitaminC: 10,
      Calcium: 221,
      Iron: 6.7,
      Potassium: 60,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 51,
      IngredientName: "Dates",
      Category: "SUPERFOODS",
      VitaminA: 10,
      VitaminC: 0.4,
      Calcium: 15,
      Iron: 0.9,
      Potassium: 656,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 52,
      IngredientName: "Ginger",
      Category: "SUPERFOODS",
      VitaminA: 0,
      VitaminC: 5,
      Calcium: 16,
      Iron: 0.6,
      Potassium: 415,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 53,
      IngredientName: "Goji berries",
      Category: "SUPERFOODS",
      VitaminA: 2905,
      VitaminC: 48,
      Calcium: 53,
      Iron: 2.1,
      Potassium: 297,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 54,
      IngredientName: "Fresh herbs",
      Category: "SUPERFOODS",
      VitaminA: 5900,
      VitaminC: 133,
      Calcium: 138,
      Iron: 5,
      Potassium: 554,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 55,
      IngredientName: "Maca",
      Category: "SUPERFOODS",
      VitaminA: 0,
      VitaminC: 2,
      Calcium: 25,
      Iron: 1.5,
      Potassium: 165,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 56,
      IngredientName: "Moringa",
      Category: "SUPERFOODS",
      VitaminA: 3780,
      VitaminC: 164,
      Calcium: 150,
      Iron: 2.5,
      Potassium: 337,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 57,
      IngredientName: "Ground stevia",
      Category: "SUPERFOODS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 0,
      Iron: 0,
      Potassium: 0,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 58,
      IngredientName: "Turmeric",
      Category: "SUPERFOODS",
      VitaminA: 0,
      VitaminC: 0.9,
      Calcium: 17,
      Iron: 5.2,
      Potassium: 208,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 59,
      IngredientName: "Vanilla",
      Category: "SUPERFOODS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 11,
      Iron: 0.1,
      Potassium: 148,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 60,
      IngredientName: "Vegan yogurt",
      Category: "SUPERFOODS",
      VitaminA: 0,
      VitaminC: 0.3,
      Calcium: 200,
      Iron: 0,
      Potassium: 180,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 61,
      IngredientName: "Mint",
      Category: "SUPERFOODS",
      VitaminA: 3388,
      VitaminC: 31.8,
      Calcium: 199,
      Iron: 8,
      Potassium: 458,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 62,
      IngredientName: "Parsley",
      Category: "SUPERFOODS",
      VitaminA: 5054,
      VitaminC: 133,
      Calcium: 138,
      Iron: 3.7,
      Potassium: 554,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 63,
      IngredientName: "Lime",
      Category: "SUPERFOODS",
      VitaminA: 50,
      VitaminC: 19.5,
      Calcium: 22,
      Iron: 0.5,
      Potassium: 68,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 64,
      IngredientName: "Lemon",
      Category: "SUPERFOODS",
      VitaminA: 22,
      VitaminC: 53,
      Calcium: 26,
      Iron: 0.6,
      Potassium: 138,
      Benefits: "gut health, vibrant skin, strong bones",
    },
    {
      IngredientID: 65,
      IngredientName: "Lime",
      Category: "SUPERFOODS",
      VitaminA: 0,
      VitaminC: 0,
      Calcium: 0,
      Iron: 0,
      Potassium: 0,
      Benefits: "gut health, vibrant skin, strong bones",
    },
  ],
  recipeIngredients: [
    {
      RecipeID: 1,
      IngredientID: 1,
      Quantity: 8.5,
    },
    {
      RecipeID: 1,
      IngredientID: 3,
      Quantity: 0.5,
    },
    {
      RecipeID: 2,
      IngredientID: 2,
      Quantity: 0.75,
    },
    {
      RecipeID: 2,
      IngredientID: 4,
      Quantity: 3,
    },
  ],
};

export function getIngredients() {
  return db.ingredients;
}
